# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Convert Markdown to HTML
        uses: ZacJW/markdown-html-action@1.1.0
        with:
          input_files: '[["status/dsa110.md"]]'
          output_files: '["dsa110.html"]'
#          builtin_stylesheet: 'style.css'
          packages: 'pymdown-extensions'
          extensions: '["pymdownx.extra"]'
      - name: Add artifact to branch
        uses: actions/download-artifact@v2
        with:
          path: dsa110.html
      - name: download artifacts
        uses: actions/checkout@v2
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Casey Law
          author_email: caseyjlaw@gmail.com
          message: 'Made dsa110.html'
          add: 'dsa110.html'
          push: true
